SHELL: zsh
SHELL_PKG: oh-my-zsh
editor: vim

oh-my-zsh:
  install: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  theme: agnoster
  rc: export ZSH=$HOME/.oh-my-zsh
  plugins: []
  options: []

functions:
  resetenv: |
    "[ -z "${VIRTUAL_ENV}" ] && return 1
    local _VENV=$(basename ${VIRTUAL_ENV})
    local _VENV_PATH="${VIRTUAL_ENV}"
    deactivate
    rm -rf "${_VENV_PATH}"
    mkvirtualenv ${_VENV}
    hash -r"

aliases:
  ll:      "ls -la"
  l:       "ll"
  python:  "python3"
  pip:     "pip3"
  ipython: "python3 -m IPython"

virtualenvs:
  oh-my-zsh:
    plugins: ["virtualenv", "virtualenvwrapper"]
  WORKON_HOME: $HOME/.virtualenvs

ruby:
  oh-my-zsh:
    plugins: ["bundler"]
  gems: [bundler]